In [1]:
import pandas as pd
df=pd.read_excel("C:\\Users\\dell\\Downloads\\Desktop\\aapl2.xlsx")
df

           Open        High         Low       Close   Adj Close     Volume
0    159.570007  160.449997  156.360001  156.809998  155.905167   76959800
1    159.369995  161.190002  158.789993  160.240005  159.315369   88748200
2    159.990005  165.520004  159.919998  165.300003  164.346176  174048100
3    167.479996  170.300003  164.529999  164.770004  163.819244  152052500
4    158.740005  164.199997  157.800003  163.759995  162.815048  136739200
5    164.020004  164.960007  159.720001  161.839996  160.906143  118023100
6    164.289993  167.880005  164.279999  165.320007  164.366058  107497000
7    169.080002  171.580002  168.339996  171.179993  170.192215  120405400
8    172.130005  175.960007  170.699997  175.080002  174.069748  116998900
9    174.910004  176.750000  173.919998  174.559998  173.552734  108923700
10   175.210007  179.630005  174.690002  179.449997  178.414520  115402700
11   181.119995  182.130005  175.529999  175.740005  174.725937  153237000
12   175.250000  177.740005  172.210007  174.330002  173.324066  139380400
13   175.110001  179.500000  172.309998  179.300003  178.265396  131063300
14   179.279999  181.139999  170.750000  172.259995  171.266006  150185800
15   169.929993  173.470001  169.690002  171.139999  170.152466  195432700
16   168.279999  170.580002  167.460007  169.750000  168.770477  107499100
17   171.559998  173.199997  169.119995  172.990005  171.991806   91185900
18   173.039993  175.860001  172.149994  175.639999  174.626511   92135300
19   175.850006  176.850006  175.270004  176.279999  175.262802   68356600
20   177.089996  180.419998  177.070007  180.330002  179.289444   74919600
21   180.160004  181.330002  178.529999  179.289993  178.255432   79144300
22   179.330002  180.630005  178.139999  179.380005  178.344925   62348900
23   179.470001  180.570007  178.089996  178.199997  177.171722   59773000
24   178.089996  179.229996  177.259995  177.570007  176.545380   64062300
25   177.830002  182.880005  177.710007  182.009995  180.959747  104487900
26   182.630005  182.940002  179.119995  179.699997  178.663071   99310400
27   179.610001  180.169998  174.639999  174.919998  173.910660   94537600
28   172.699997  175.300003  171.639999  172.000000  171.007507   96904000
29   172.889999  174.139999  171.029999  172.169998  171.176529   86709100
..          ...         ...         ...         ...         ...        ...
222  144.309998  144.520004  138.190002  138.380005  138.150833   88598000
223  141.070007  142.899994  140.270004  142.410004  142.174164   85250900
224  145.490005  146.699997  140.610001  143.750000  143.511932   99136600
225  141.690002  144.949997  141.500000  143.860001  143.621750   61758300
226  143.020004  145.889999  142.649994  143.389999  143.152527   64522000
227  142.869995  147.850006  142.649994  147.270004  147.026108   86548600
228  147.190002  150.229996  146.000000  149.449997  149.202484   75981900
229  150.089996  152.490005  149.360001  152.339996  152.087708   74732300
230  150.960007  151.990005  148.039993  149.350006  149.102661   88194300
231  148.070007  149.050003  144.130005  144.800003  144.560196  109180200
232  148.199997  157.500000  147.820007  155.740005  155.482086  164762400
233  153.160004  154.240005  151.919998  153.339996  153.086044   97943200
234  155.080002  155.449997  149.130005  150.649994  150.400497   80379300
235  148.949997  152.169998  145.000000  145.029999  144.789810   93604600
236  142.059998  142.800003  138.750000  138.880005  138.650009   97918500
237  142.089996  142.669998  134.380005  138.380005  138.380005  140716700
238  137.110001  139.149994  135.669998  138.919998  138.919998   83374600
239  140.410004  141.429993  137.490005  139.500000  139.500000   89908500
240  138.500000  138.550003  134.589996  134.869995  134.869995   74917800
241  141.240005  146.869995  139.500000  146.869995  146.869995  118854000
242  145.820007  150.009995  144.369995  149.699997  149.699997   93903800
243  148.970001  150.279999  147.429993  148.279999  148.279999   73374100
244  152.220001  153.589996  148.559998  150.039993  150.039993   89868300
245  149.130005  149.869995  147.289993  148.789993  148.789993   64218300
246  146.429993  151.479996  146.149994  150.720001  150.720001   80389400
247  152.309998  152.699997  149.970001  151.289993  151.289993   74794600
248  150.160004  150.369995  147.720001  148.009995  148.009995   58724100
249  148.130005  150.419998  146.929993  150.179993  150.179993   51804100
250  149.449997  151.830002  149.339996  151.070007  151.070007   58301400
251  148.309998  148.880005  147.119995  148.110001  148.110001   35195900

[252 rows x 6 columns]

In [2]:
rng=pd.date_range(start="6/1/2017",end="5/20/2018",freq='B')
rng

DatetimeIndex(['2017-06-01', '2017-06-02', '2017-06-05', '2017-06-06',
               '2017-06-07', '2017-06-08', '2017-06-09', '2017-06-12',
               '2017-06-13', '2017-06-14',
               ...
               '2018-05-07', '2018-05-08', '2018-05-09', '2018-05-10',
               '2018-05-11', '2018-05-14', '2018-05-15', '2018-05-16',
               '2018-05-17', '2018-05-18'],
              dtype='datetime64[ns]', length=252, freq='B')

In [3]:
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

usb=CustomBusinessDay(calendar=USFederalHolidayCalendar())
usb

In [11]:
rng=pd.date_range(start="5/1/2017",end="5/1/2018",freq=usb)
rng

DatetimeIndex(['2017-05-01', '2017-05-02', '2017-05-03', '2017-05-04',
               '2017-05-05', '2017-05-08', '2017-05-09', '2017-05-10',
               '2017-05-11', '2017-05-12',
               ...
               '2018-04-18', '2018-04-19', '2018-04-20', '2018-04-23',
               '2018-04-24', '2018-04-25', '2018-04-26', '2018-04-27',
               '2018-04-30', '2018-05-01'],
              dtype='datetime64[ns]', length=252, freq='C')

In [12]:
df.set_index(rng,inplace=True)
df

,Open,High,Low,Close,Adj Close,Volume
2017-05-01,159.570007,160.449997,156.360001,156.809998,155.905167,76959800
2017-05-02,159.369995,161.190002,158.789993,160.240005,159.315369,88748200
2017-05-03,159.990005,165.520004,159.919998,165.300003,164.346176,174048100
2017-05-04,167.479996,170.300003,164.529999,164.770004,163.819244,152052500
2017-05-05,158.740005,164.199997,157.800003,163.759995,162.815048,136739200
2017-05-08,164.020004,164.960007,159.720001,161.839996,160.906143,118023100
2017-05-09,164.289993,167.880005,164.279999,165.320007,164.366058,107497000
2017-05-10,169.080002,171.580002,168.339996,171.179993,170.192215,120405400
2017-05-11,172.130005,175.960007,170.699997,175.080002,174.069748,116998900
2017-05-12,174.910004,176.750000,173.919998,174.559998,173.552734,108923700
2017-05-15,175.210007,179.630005,174.690002,179.449997,178.414520,115402700
2017-05-16,181.119995,182.130005,175.529999,175.740005,174.725937,153237000
2017-05-17,175.250000,177.740005,172.210007,174.330002,173.324066,139380400
2017-05-18,175.110001,179.500000,172.309998,179.300003,178.265396,131063300
2017-05-19,179.279999,181.139999,170.750000,172.259995,171.266006,150185800
2017-05-22,169.929993,173.470001,169.690002,171.139999,170.152466,195432700
2017-05-23,168.279999,170.580002,167.460007,169.750000,168.770477,107499100
2017-05-24,171.559998,173.199997,169.119995,172.990005,171.991806,91185900
2017-05-25,173.039993,175.860001,172.149994,175.639999,174.626511,92135300
2017-05-26,175.850006,176.850006,175.270004,176.279999,175.262802,68356600
2017-05-30,177.089996,180.419998,177.070007,180.330002,179.289444,74919600
2017-05-31,180.160004,181.330002,178.529999,179.289993,178.255432,79144300
2017-06-01,179.330002,180.630005,178.139999,179.380005,178.344925,62348900
2017-06-02,179.470001,180.570007,178.089996,178.199997,177.171722,59773000
2017-06-05,178.089996,179.229996,177.259995,177.570007,176.545380,64062300
2017-06-06,177.830002,182.880005,177.710007,182.009995,180.959747,104487900
2017-06-07,182.630005,182.940002,179.119995,179.699997,178.663071,99310400
2017-06-08,179.610001,180.169998,174.639999,174.919998,173.910660,94537600
2017-06-09,172.699997,175.300003,171.639999,172.000000,171.007507,96904000
2017-06-12,172.889999,174.139999,171.029999,172.169998,171.176529,86709100
...,...,...,...,...,...,...
2018-03-21,144.309998,144.520004,138.190002,138.380005,138.150833,88598000
2018-03-22,141.070007,142.899994,140.270004,142.410004,142.174164,85250900
2018-03-23,145.490005,146.699997,140.610001,143.750000,143.511932,99136600
2018-03-26,141.690002,144.949997,141.500000,143.860001,143.621750,61758300
2018-03-27,143.020004,145.889999,142.649994,143.389999,143.152527,64522000
2018-03-28,142.869995,147.850006,142.649994,147.270004,147.026108,86548600
2018-03-29,147.190002,150.229996,146.000000,149.449997,149.202484,75981900
2018-03-30,150.089996,152.490005,149.360001,152.339996,152.087708,74732300
2018-04-02,150.960007,151.990005,148.039993,149.350006,149.102661,88194300
2018-04-03,148.070007,149.050003,144.130005,144.800003,144.560196,109180200
2018-04-04,148.199997,157.500000,147.820007,155.740005,155.482086,164762400
2018-04-05,153.160004,154.240005,151.919998,153.339996,153.086044,97943200
2018-04-06,155.080002,155.449997,149.130005,150.649994,150.400497,80379300
2018-04-09,148.949997,152.169998,145.000000,145.029999,144.789810,93604600
2018-04-10,142.059998,142.800003,138.750000,138.880005,138.650009,97918500
2018-04-11,142.089996,142.669998,134.380005,138.380005,138.380005,140716700
2018-04-12,137.110001,139.149994,135.669998,138.919998,138.919998,83374600
2018-04-13,140.410004,141.429993,137.490005,139.500000,139.500000,89908500
2018-04-16,138.500000,138.550003,134.589996,134.869995,134.869995,74917800
2018-04-17,141.240005,146.869995,139.500000,146.869995,146.869995,118854000
2018-04-18,145.820007,150.009995,144.369995,149.699997,149.699997,93903800
2018-04-19,148.970001,150.279999,147.429993,148.279999,148.279999,73374100
2018-04-20,152.220001,153.589996,148.559998,150.039993,150.039993,89868300
2018-04-23,149.130005,149.869995,147.289993,148.789993,148.789993,64218300
2018-04-24,146.429993,151.479996,146.149994,150.720001,150.720001,80389400
2018-04-25,152.309998,152.699997,149.970001,151.289993,151.289993,74794600
2018-04-26,150.160004,150.369995,147.720001,148.009995,148.009995,58724100
2018-04-27,148.130005,150.419998,146.929993,150.179993,150.179993,51804100
2018-04-30,149.449997,151.830002,149.339996,151.070007,151.070007,58301400
2018-05-01,148.309998,148.880005,147.119995,148.110001,148.110001,35195900

In [9]:
import pandas as pd
from pandas.tseries.holiday import AbstractHolidayCalendar,nearest_workday,Holiday
from pandas.tseries.offsets import CustomBusinessDay
class myBirthdayCalendar(AbstractHolidayCalendar):
    """
    US Federal Government Holiday Calendar based on rules specified by:
    https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/
    """

    rules = [
        Holiday("vinay's birthday", month=11, day=16)#, observance=nearest_workday),
        
    ]
myc=CustomBusinessDay(calendar=myBirthdayCalendar())
myc

In [10]:
pd.date_range(start="11/04/2022",end="30/11/2022",freq=myc)

DatetimeIndex(['2022-11-04', '2022-11-07', '2022-11-08', '2022-11-09',
               '2022-11-10', '2022-11-11', '2022-11-14', '2022-11-15',
               '2022-11-17', '2022-11-18', '2022-11-21', '2022-11-22',
               '2022-11-23', '2022-11-24', '2022-11-25', '2022-11-28',
               '2022-11-29', '2022-11-30'],
              dtype='datetime64[ns]', freq='C')

In [12]:
#to change weekdays manually,shift+tab- gives script and from that we can customize the weekdays

b=CustomBusinessDay(weekmask='Sun Mon Tue Wed Thu',holidays=["2022-12-04"])
pd.date_range(start="11/04/2022",end="30/11/2022",freq=b)

DatetimeIndex(['2022-11-06', '2022-11-07', '2022-11-08', '2022-11-09',
               '2022-11-10', '2022-11-13', '2022-11-14', '2022-11-15',
               '2022-11-16', '2022-11-17', '2022-11-20', '2022-11-21',
               '2022-11-22', '2022-11-23', '2022-11-24', '2022-11-27',
               '2022-11-28', '2022-11-29', '2022-11-30'],
              dtype='datetime64[ns]', freq='C')