In [2]:
import pandas as pd
y=pd.Period('2021')
y

Period('2021', 'A-DEC')

In [6]:
dir(y)

['__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_add_delta',
 '_from_ordinal',
 '_maybe_convert_freq',
 '_typ',
 'asfreq',
 'day',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'end_time',
 'freq',
 'freqstr',
 'hour',
 'is_leap_year',
 'minute',
 'month',
 'now',
 'ordinal',
 'quarter',
 'qyear',
 'second',
 'start_time',
 'strftime',
 'to_timestamp',
 'week',
 'weekday',
 'weekofyear',
 'year']

In [7]:
y.start_time

Timestamp('2021-01-01 00:00:00')

In [8]:
y.end_time

Timestamp('2021-12-31 23:59:59.999999999')

In [9]:
m=pd.Period('2021-1',freq='M')
m

Period('2021-01', 'M')

In [10]:
m+1            #gives following month based on frequency

Period('2021-02', 'M')

In [17]:
d=pd.Period('2021-12-31 23:00:00',freq='D')
d

Period('2021-12-31', 'D')

In [16]:
d+1

Period('2022-01-01', 'D')

In [18]:
d=pd.Period('2021-12-31 23:00:00',freq='H')
d

Period('2021-12-31 23:00', 'H')

In [22]:
d+pd.offsets.Hour(5)

Period('2022-01-01 04:00', 'H')

In [23]:
q=pd.Period('2021Q1','Q-DEC')
q

Period('2021Q1', 'Q-DEC')

In [24]:
q+1           #give start and end time, gives results based on the given periods

Period('2021Q2', 'Q-DEC')

In [25]:
q=pd.Period('2021Q1',freq='Q-JAN')          #if fiscal is different
q

Period('2021Q1', 'Q-JAN')

In [27]:
q.start_time

Timestamp('2020-02-01 00:00:00')

In [28]:
q.end_time

Timestamp('2020-04-30 23:59:59.999999999')

In [29]:
q.asfreq('M',how="end")       # to convert frequency to different frequency

Period('2020-04', 'M')

In [30]:
q.asfreq('M',how="start")

Period('2020-02', 'M')

In [31]:
q2=pd.Period('2021Q2',freq='Q-JAN')
q2

Period('2021Q2', 'Q-JAN')

In [32]:
q2-q        #works only with same frequencies(operations)

In [34]:
idx=pd.period_range('2011','2017',freq='Q')
idx

PeriodIndex(['2011Q1', '2011Q2', '2011Q3', '2011Q4', '2012Q1', '2012Q2',
             '2012Q3', '2012Q4', '2013Q1', '2013Q2', '2013Q3', '2013Q4',
             '2014Q1', '2014Q2', '2014Q3', '2014Q4', '2015Q1', '2015Q2',
             '2015Q3', '2015Q4', '2016Q1', '2016Q2', '2016Q3', '2016Q4',
             '2017Q1'],
            dtype='period[Q-DEC]', freq='Q-DEC')

In [35]:
idx=pd.period_range('2011','2017',freq='Q-JAN')      #for varying fiscal years Q-JAN
idx

PeriodIndex(['2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1',
             '2013Q2', '2013Q3', '2013Q4', '2014Q1', '2014Q2', '2014Q3',
             '2014Q4', '2015Q1', '2015Q2', '2015Q3', '2015Q4', '2016Q1',
             '2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3',
             '2017Q4'],
            dtype='period[Q-JAN]', freq='Q-JAN')

In [36]:
idx[0].start_time     #start of fiscal year for above quarter 2011Q4

Timestamp('2010-11-01 00:00:00')

In [37]:
idx[0].start_time     #end of fiscal year above quarter  2011Q4

Timestamp('2010-11-01 00:00:00')

In [39]:
idx=pd.period_range('2011',periods=10,freq='Q-JAN')      #for varying fiscal years Q-JAN
idx

PeriodIndex(['2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1',
             '2013Q2', '2013Q3', '2013Q4', '2014Q1'],
            dtype='period[Q-JAN]', freq='Q-JAN')

In [40]:
import numpy as np                                 #numpy function to create series
ps=pd.Series(np.random.randn(len(idx)),idx)
ps

2011Q4   -0.814936
2012Q1   -0.708632
2012Q2    0.839669
2012Q3   -2.378949
2012Q4   -0.347669
2013Q1   -2.957832
2013Q2   -0.103840
2013Q3    1.823248
2013Q4   -0.964301
2014Q1    0.865721
Freq: Q-JAN, dtype: float64

In [41]:
ps.index

PeriodIndex(['2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1',
             '2013Q2', '2013Q3', '2013Q4', '2014Q1'],
            dtype='period[Q-JAN]', freq='Q-JAN')

In [42]:
ps['2011']

2011Q4   -0.814936
2012Q1   -0.708632
2012Q2    0.839669
2012Q3   -2.378949
2012Q4   -0.347669
Freq: Q-JAN, dtype: float64

In [43]:
ps['2011':'2013']

2011Q4   -0.814936
2012Q1   -0.708632
2012Q2    0.839669
2012Q3   -2.378949
2012Q4   -0.347669
2013Q1   -2.957832
2013Q2   -0.103840
2013Q3    1.823248
2013Q4   -0.964301
2014Q1    0.865721
Freq: Q-JAN, dtype: float64

In [44]:
pst=ps.to_timestamp()     #gives datetime index from period index
pst

2010-11-01   -0.814936
2011-02-01   -0.708632
2011-05-01    0.839669
2011-08-01   -2.378949
2011-11-01   -0.347669
2012-02-01   -2.957832
2012-05-01   -0.103840
2012-08-01    1.823248
2012-11-01   -0.964301
2013-02-01    0.865721
Freq: QS-NOV, dtype: float64

In [45]:
pst.index

DatetimeIndex(['2010-11-01', '2011-02-01', '2011-05-01', '2011-08-01',
               '2011-11-01', '2012-02-01', '2012-05-01', '2012-08-01',
               '2012-11-01', '2013-02-01'],
              dtype='datetime64[ns]', freq='QS-NOV')

In [47]:
pst.to_period()           #to getback to period index

2010Q4   -0.814936
2011Q1   -0.708632
2011Q2    0.839669
2011Q3   -2.378949
2011Q4   -0.347669
2012Q1   -2.957832
2012Q2   -0.103840
2012Q3    1.823248
2012Q4   -0.964301
2013Q1    0.865721
Freq: Q-DEC, dtype: float64

In [57]:
import pandas as pd
df=pd.read_excel("C:\\Users\\dell\\Downloads\\Desktop\\AAPL2.xlsx")
df

           Open        High         Low       Close   Adj Close     Volume
0    159.570007  160.449997  156.360001  156.809998  155.905167   76959800
1    159.369995  161.190002  158.789993  160.240005  159.315369   88748200
2    159.990005  165.520004  159.919998  165.300003  164.346176  174048100
3    167.479996  170.300003  164.529999  164.770004  163.819244  152052500
4    158.740005  164.199997  157.800003  163.759995  162.815048  136739200
5    164.020004  164.960007  159.720001  161.839996  160.906143  118023100
6    164.289993  167.880005  164.279999  165.320007  164.366058  107497000
7    169.080002  171.580002  168.339996  171.179993  170.192215  120405400
8    172.130005  175.960007  170.699997  175.080002  174.069748  116998900
9    174.910004  176.750000  173.919998  174.559998  173.552734  108923700
10   175.210007  179.630005  174.690002  179.449997  178.414520  115402700
11   181.119995  182.130005  175.529999  175.740005  174.725937  153237000
12   175.250000  177.740005  172.210007  174.330002  173.324066  139380400
13   175.110001  179.500000  172.309998  179.300003  178.265396  131063300
14   179.279999  181.139999  170.750000  172.259995  171.266006  150185800
15   169.929993  173.470001  169.690002  171.139999  170.152466  195432700
16   168.279999  170.580002  167.460007  169.750000  168.770477  107499100
17   171.559998  173.199997  169.119995  172.990005  171.991806   91185900
18   173.039993  175.860001  172.149994  175.639999  174.626511   92135300
19   175.850006  176.850006  175.270004  176.279999  175.262802   68356600
20   177.089996  180.419998  177.070007  180.330002  179.289444   74919600
21   180.160004  181.330002  178.529999  179.289993  178.255432   79144300
22   179.330002  180.630005  178.139999  179.380005  178.344925   62348900
23   179.470001  180.570007  178.089996  178.199997  177.171722   59773000
24   178.089996  179.229996  177.259995  177.570007  176.545380   64062300
25   177.830002  182.880005  177.710007  182.009995  180.959747  104487900
26   182.630005  182.940002  179.119995  179.699997  178.663071   99310400
27   179.610001  180.169998  174.639999  174.919998  173.910660   94537600
28   172.699997  175.300003  171.639999  172.000000  171.007507   96904000
29   172.889999  174.139999  171.029999  172.169998  171.176529   86709100
..          ...         ...         ...         ...         ...        ...
222  144.309998  144.520004  138.190002  138.380005  138.150833   88598000
223  141.070007  142.899994  140.270004  142.410004  142.174164   85250900
224  145.490005  146.699997  140.610001  143.750000  143.511932   99136600
225  141.690002  144.949997  141.500000  143.860001  143.621750   61758300
226  143.020004  145.889999  142.649994  143.389999  143.152527   64522000
227  142.869995  147.850006  142.649994  147.270004  147.026108   86548600
228  147.190002  150.229996  146.000000  149.449997  149.202484   75981900
229  150.089996  152.490005  149.360001  152.339996  152.087708   74732300
230  150.960007  151.990005  148.039993  149.350006  149.102661   88194300
231  148.070007  149.050003  144.130005  144.800003  144.560196  109180200
232  148.199997  157.500000  147.820007  155.740005  155.482086  164762400
233  153.160004  154.240005  151.919998  153.339996  153.086044   97943200
234  155.080002  155.449997  149.130005  150.649994  150.400497   80379300
235  148.949997  152.169998  145.000000  145.029999  144.789810   93604600
236  142.059998  142.800003  138.750000  138.880005  138.650009   97918500
237  142.089996  142.669998  134.380005  138.380005  138.380005  140716700
238  137.110001  139.149994  135.669998  138.919998  138.919998   83374600
239  140.410004  141.429993  137.490005  139.500000  139.500000   89908500
240  138.500000  138.550003  134.589996  134.869995  134.869995   74917800
241  141.240005  146.869995  139.500000  146.869995  146.869995  118854000
242  145.820007  150.009995  144.369995  149.699997  149.699997   93903800
243  148.970001  150.279999  147.429993  148.279999  148.279999   73374100
244  152.220001  153.589996  148.559998  150.039993  150.039993   89868300
245  149.130005  149.869995  147.289993  148.789993  148.789993   64218300
246  146.429993  151.479996  146.149994  150.720001  150.720001   80389400
247  152.309998  152.699997  149.970001  151.289993  151.289993   74794600
248  150.160004  150.369995  147.720001  148.009995  148.009995   58724100
249  148.130005  150.419998  146.929993  150.179993  150.179993   51804100
250  149.449997  151.830002  149.339996  151.070007  151.070007   58301400
251  148.309998  148.880005  147.119995  148.110001  148.110001   35195900

[252 rows x 6 columns]

In [58]:
df.set_index('Open',inplace=True)
df

                  High         Low       Close   Adj Close     Volume
Open
159.570007  160.449997  156.360001  156.809998  155.905167   76959800
159.369995  161.190002  158.789993  160.240005  159.315369   88748200
159.990005  165.520004  159.919998  165.300003  164.346176  174048100
167.479996  170.300003  164.529999  164.770004  163.819244  152052500
158.740005  164.199997  157.800003  163.759995  162.815048  136739200
164.020004  164.960007  159.720001  161.839996  160.906143  118023100
164.289993  167.880005  164.279999  165.320007  164.366058  107497000
169.080002  171.580002  168.339996  171.179993  170.192215  120405400
172.130005  175.960007  170.699997  175.080002  174.069748  116998900
174.910004  176.750000  173.919998  174.559998  173.552734  108923700
175.210007  179.630005  174.690002  179.449997  178.414520  115402700
181.119995  182.130005  175.529999  175.740005  174.725937  153237000
175.250000  177.740005  172.210007  174.330002  173.324066  139380400
175.110001  179.500000  172.309998  179.300003  178.265396  131063300
179.279999  181.139999  170.750000  172.259995  171.266006  150185800
169.929993  173.470001  169.690002  171.139999  170.152466  195432700
168.279999  170.580002  167.460007  169.750000  168.770477  107499100
171.559998  173.199997  169.119995  172.990005  171.991806   91185900
173.039993  175.860001  172.149994  175.639999  174.626511   92135300
175.850006  176.850006  175.270004  176.279999  175.262802   68356600
177.089996  180.419998  177.070007  180.330002  179.289444   74919600
180.160004  181.330002  178.529999  179.289993  178.255432   79144300
179.330002  180.630005  178.139999  179.380005  178.344925   62348900
179.470001  180.570007  178.089996  178.199997  177.171722   59773000
178.089996  179.229996  177.259995  177.570007  176.545380   64062300
177.830002  182.880005  177.710007  182.009995  180.959747  104487900
182.630005  182.940002  179.119995  179.699997  178.663071   99310400
179.610001  180.169998  174.639999  174.919998  173.910660   94537600
172.699997  175.300003  171.639999  172.000000  171.007507   96904000
172.889999  174.139999  171.029999  172.169998  171.176529   86709100
...                ...         ...         ...         ...        ...
144.309998  144.520004  138.190002  138.380005  138.150833   88598000
141.070007  142.899994  140.270004  142.410004  142.174164   85250900
145.490005  146.699997  140.610001  143.750000  143.511932   99136600
141.690002  144.949997  141.500000  143.860001  143.621750   61758300
143.020004  145.889999  142.649994  143.389999  143.152527   64522000
142.869995  147.850006  142.649994  147.270004  147.026108   86548600
147.190002  150.229996  146.000000  149.449997  149.202484   75981900
150.089996  152.490005  149.360001  152.339996  152.087708   74732300
150.960007  151.990005  148.039993  149.350006  149.102661   88194300
148.070007  149.050003  144.130005  144.800003  144.560196  109180200
148.199997  157.500000  147.820007  155.740005  155.482086  164762400
153.160004  154.240005  151.919998  153.339996  153.086044   97943200
155.080002  155.449997  149.130005  150.649994  150.400497   80379300
148.949997  152.169998  145.000000  145.029999  144.789810   93604600
142.059998  142.800003  138.750000  138.880005  138.650009   97918500
142.089996  142.669998  134.380005  138.380005  138.380005  140716700
137.110001  139.149994  135.669998  138.919998  138.919998   83374600
140.410004  141.429993  137.490005  139.500000  139.500000   89908500
138.500000  138.550003  134.589996  134.869995  134.869995   74917800
141.240005  146.869995  139.500000  146.869995  146.869995  118854000
145.820007  150.009995  144.369995  149.699997  149.699997   93903800
148.970001  150.279999  147.429993  148.279999  148.279999   73374100
152.220001  153.589996  148.559998  150.039993  150.039993   89868300
149.130005  149.869995  147.289993  148.789993  148.789993   64218300
146.429993  151.479996  146.149994  150.720001  150.720001   80389400
152.309998  152.699997  149.970001  151.289993  151.289993   74794600
150.160004  150.369995  147.720001  148.009995  148.009995   58724100
148.130005  150.419998  146.929993  150.179993  150.179993   51804100
149.449997  151.830002  149.339996  151.070007  151.070007   58301400
148.309998  148.880005  147.119995  148.110001  148.110001   35195900

[252 rows x 5 columns]

In [60]:
df=df.T #changes rows as colums and columns as rows
df

                  High         Low       Close   Adj Close       Volume
Open
159.570007  160.449997  156.360001  156.809998  155.905167   76959800.0
159.369995  161.190002  158.789993  160.240005  159.315369   88748200.0
159.990005  165.520004  159.919998  165.300003  164.346176  174048100.0
167.479996  170.300003  164.529999  164.770004  163.819244  152052500.0
158.740005  164.199997  157.800003  163.759995  162.815048  136739200.0
164.020004  164.960007  159.720001  161.839996  160.906143  118023100.0
164.289993  167.880005  164.279999  165.320007  164.366058  107497000.0
169.080002  171.580002  168.339996  171.179993  170.192215  120405400.0
172.130005  175.960007  170.699997  175.080002  174.069748  116998900.0
174.910004  176.750000  173.919998  174.559998  173.552734  108923700.0
175.210007  179.630005  174.690002  179.449997  178.414520  115402700.0
181.119995  182.130005  175.529999  175.740005  174.725937  153237000.0
175.250000  177.740005  172.210007  174.330002  173.324066  139380400.0
175.110001  179.500000  172.309998  179.300003  178.265396  131063300.0
179.279999  181.139999  170.750000  172.259995  171.266006  150185800.0
169.929993  173.470001  169.690002  171.139999  170.152466  195432700.0
168.279999  170.580002  167.460007  169.750000  168.770477  107499100.0
171.559998  173.199997  169.119995  172.990005  171.991806   91185900.0
173.039993  175.860001  172.149994  175.639999  174.626511   92135300.0
175.850006  176.850006  175.270004  176.279999  175.262802   68356600.0
177.089996  180.419998  177.070007  180.330002  179.289444   74919600.0
180.160004  181.330002  178.529999  179.289993  178.255432   79144300.0
179.330002  180.630005  178.139999  179.380005  178.344925   62348900.0
179.470001  180.570007  178.089996  178.199997  177.171722   59773000.0
178.089996  179.229996  177.259995  177.570007  176.545380   64062300.0
177.830002  182.880005  177.710007  182.009995  180.959747  104487900.0
182.630005  182.940002  179.119995  179.699997  178.663071   99310400.0
179.610001  180.169998  174.639999  174.919998  173.910660   94537600.0
172.699997  175.300003  171.639999  172.000000  171.007507   96904000.0
172.889999  174.139999  171.029999  172.169998  171.176529   86709100.0
...                ...         ...         ...         ...          ...
144.309998  144.520004  138.190002  138.380005  138.150833   88598000.0
141.070007  142.899994  140.270004  142.410004  142.174164   85250900.0
145.490005  146.699997  140.610001  143.750000  143.511932   99136600.0
141.690002  144.949997  141.500000  143.860001  143.621750   61758300.0
143.020004  145.889999  142.649994  143.389999  143.152527   64522000.0
142.869995  147.850006  142.649994  147.270004  147.026108   86548600.0
147.190002  150.229996  146.000000  149.449997  149.202484   75981900.0
150.089996  152.490005  149.360001  152.339996  152.087708   74732300.0
150.960007  151.990005  148.039993  149.350006  149.102661   88194300.0
148.070007  149.050003  144.130005  144.800003  144.560196  109180200.0
148.199997  157.500000  147.820007  155.740005  155.482086  164762400.0
153.160004  154.240005  151.919998  153.339996  153.086044   97943200.0
155.080002  155.449997  149.130005  150.649994  150.400497   80379300.0
148.949997  152.169998  145.000000  145.029999  144.789810   93604600.0
142.059998  142.800003  138.750000  138.880005  138.650009   97918500.0
142.089996  142.669998  134.380005  138.380005  138.380005  140716700.0
137.110001  139.149994  135.669998  138.919998  138.919998   83374600.0
140.410004  141.429993  137.490005  139.500000  139.500000   89908500.0
138.500000  138.550003  134.589996  134.869995  134.869995   74917800.0
141.240005  146.869995  139.500000  146.869995  146.869995  118854000.0
145.820007  150.009995  144.369995  149.699997  149.699997   93903800.0
148.970001  150.279999  147.429993  148.279999  148.279999   73374100.0
152.220001  153.589996  148.559998  150.039993  150.039993   89868300.0
149.130005  149.869995  147.289993  148.789993  148.789993   64218300.0
146.429993  151.479996  146.149994  150.720001  150.720001   80389400.0
152.309998  152.699997  149.970001  151.289993  151.289993   74794600.0
150.160004  150.369995  147.720001  148.009995  148.009995   58724100.0
148.130005  150.419998  146.929993  150.179993  150.179993   51804100.0
149.449997  151.830002  149.339996  151.070007  151.070007   58301400.0
148.309998  148.880005  147.119995  148.110001  148.110001   35195900.0

[252 rows x 5 columns]

In [61]:
df.index=pd.PeriodIndex(df.index,freq='Q-JAN')

TypeError: PeriodIndex does not allow floating point in construction

In [63]:
df['start_date']=df.index.map(lamda x: x.start_time)     #takes functionas argument

SyntaxError: invalid syntax (<ipython-input-63-9d2775b328df>, line 1)

In [ ]:
df['end_date']=df.index.map(lamda x: x.end_time)